# Generated by Django 5.2.17 on 2026-09-22 15:20

import core.uploads
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acolhido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('nome_social', models.CharField(blank=True, help_text='Preencha se a pessoa é chamada por outro nome.', max_length=150, verbose_name='nome social')),
                ('nascimento', models.DateField(verbose_name='data de nascimento')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='sexo')),
                ('naturalidade', models.CharField(blank=True, max_length=100, verbose_name='naturalidade')),
                ('foto', models.ImageField(blank=True, upload_to=core.uploads.CaminhoOpaco('acolhidos/fotos'), validators=[core.uploads.validar_imagem], verbose_name='foto')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('certidao_nascimento', models.CharField(blank=True, max_length=50, verbose_name='certidão de nascimento')),
                ('cartao_sus', models.CharField(blank=True, max_length=20, verbose_name='cartão SUS')),
                ('status', models.CharField(choices=[('ACOLHIDO', 'Acolhido'), ('DESLIGADO', 'Desligado')], default='ACOLHIDO', max_length=10, verbose_name='situação')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'acolhido',
                'verbose_name_plural': 'acolhidos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAcolhido',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('nome_social', models.CharField(blank=True, help_text='Preencha se a pessoa é chamada por outro nome.', max_length=150, verbose_name='nome social')),
                ('nascimento', models.DateField(verbose_name='data de nascimento')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, verbose_name='sexo')),
                ('naturalidade', models.CharField(blank=True, max_length=100, verbose_name='naturalidade')),
                ('foto', models.TextField(blank=True, max_length=100, validators=[core.uploads.validar_imagem], verbose_name='foto')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('certidao_nascimento', models.CharField(blank=True, max_length=50, verbose_name='certidão de nascimento')),
                ('cartao_sus', models.CharField(blank=True, max_length=20, verbose_name='cartão SUS')),
                ('status', models.CharField(choices=[('ACOLHIDO', 'Acolhido'), ('DESLIGADO', 'Desligado')], default='ACOLHIDO', max_length=10, verbose_name='situação')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical acolhido',
                'verbose_name_plural': 'historical acolhidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=150, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=80, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'responsável',
                'verbose_name_plural': 'responsáveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VinculoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('parentesco', models.CharField(max_length=50, verbose_name='parentesco')),
                ('e_guardiao', models.BooleanField(default=False, verbose_name='é guardião legal')),
                ('autorizado_visita', models.BooleanField(default=True, verbose_name='autorizado a visitar')),
                ('autorizado_retirar', models.BooleanField(default=False, verbose_name='autorizado a retirar')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('acolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='acolhidos.acolhido')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='acolhidos.responsavel')),
            ],
            options={
                'verbose_name': 'vínculo familiar',
                'verbose_name_plural': 'vínculos familiares',
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('acolhido', 'responsavel'), name='vinculo_unico_por_par')],
            },
        ),
    ]
