# Generated by Django 5.2.17 on 2026-09-22 15:22

import core.uploads
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('data_assinatura', models.DateField(verbose_name='data da assinatura')),
                ('finalidade', models.TextField(default='Registro administrativo do acolhimento e prestação de contas aos órgãos de controle.', verbose_name='finalidade declarada')),
                ('termo_assinado', models.FileField(blank=True, upload_to=core.uploads.CaminhoOpaco('acolhidos/consentimentos'), validators=[core.uploads.validar_documento], verbose_name='termo assinado')),
                ('acolhido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimento', to='acolhidos.acolhido')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos', to='acolhidos.responsavel')),
            ],
            options={
                'verbose_name': 'consentimento',
                'verbose_name_plural': 'consentimentos',
            },
        ),
        migrations.CreateModel(
            name='DadosSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=3, verbose_name='tipo sanguíneo')),
                ('alergias', models.TextField(blank=True, verbose_name='alergias')),
                ('condicoes', models.TextField(blank=True, verbose_name='condições de saúde')),
                ('plano_saude', models.CharField(blank=True, max_length=100, verbose_name='plano de saúde')),
                ('acolhido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saude', to='acolhidos.acolhido')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'dados de saúde',
                'verbose_name_plural': 'dados de saúde',
            },
        ),
        migrations.CreateModel(
            name='DocumentoAcolhido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('arquivo', models.FileField(upload_to=core.uploads.CaminhoOpaco('acolhidos/documentos'), validators=[core.uploads.validar_documento], verbose_name='arquivo')),
                ('tipo', models.CharField(max_length=80, verbose_name='tipo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('acolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='acolhidos.acolhido')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('escola', models.CharField(max_length=150, verbose_name='escola')),
                ('serie', models.CharField(max_length=50, verbose_name='série')),
                ('turno', models.CharField(blank=True, choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, verbose_name='turno')),
                ('ano_letivo', models.PositiveIntegerField(verbose_name='ano letivo')),
                ('acolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolaridades', to='acolhidos.acolhido')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'escolaridade',
                'verbose_name_plural': 'escolaridades',
                'ordering': ['-ano_letivo'],
            },
        ),
        migrations.CreateModel(
            name='FichaAcolhimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('data_entrada', models.DateField(verbose_name='data de entrada')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo do acolhimento')),
                ('orgao_requisitante', models.CharField(blank=True, max_length=150, verbose_name='órgão requisitante')),
                ('processo_numero', models.CharField(blank=True, max_length=50, verbose_name='número do processo')),
                ('vara', models.CharField(blank=True, max_length=100, verbose_name='vara')),
                ('medida_protetiva', models.TextField(blank=True, verbose_name='medida protetiva')),
                ('data_desligamento', models.DateField(blank=True, null=True, verbose_name='data de desligamento')),
                ('destino', models.CharField(blank=True, max_length=150, verbose_name='destino após o desligamento')),
                ('acolhido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='acolhidos.acolhido')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'ficha de acolhimento',
                'verbose_name_plural': 'fichas de acolhimento',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDadosSaude',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=3, verbose_name='tipo sanguíneo')),
                ('alergias', models.TextField(blank=True, verbose_name='alergias')),
                ('condicoes', models.TextField(blank=True, verbose_name='condições de saúde')),
                ('plano_saude', models.CharField(blank=True, max_length=100, verbose_name='plano de saúde')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('acolhido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='acolhidos.acolhido')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dados de saúde',
                'verbose_name_plural': 'historical dados de saúde',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFichaAcolhimento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('data_entrada', models.DateField(verbose_name='data de entrada')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo do acolhimento')),
                ('orgao_requisitante', models.CharField(blank=True, max_length=150, verbose_name='órgão requisitante')),
                ('processo_numero', models.CharField(blank=True, max_length=50, verbose_name='número do processo')),
                ('vara', models.CharField(blank=True, max_length=100, verbose_name='vara')),
                ('medida_protetiva', models.TextField(blank=True, verbose_name='medida protetiva')),
                ('data_desligamento', models.DateField(blank=True, null=True, verbose_name='data de desligamento')),
                ('destino', models.CharField(blank=True, max_length=150, verbose_name='destino após o desligamento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('acolhido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='acolhidos.acolhido')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ficha de acolhimento',
                'verbose_name_plural': 'historical fichas de acolhimento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('nome', models.CharField(max_length=120, verbose_name='medicamento')),
                ('dosagem', models.CharField(max_length=60, verbose_name='dosagem')),
                ('frequencia', models.CharField(help_text='Ex.: 8h e 20h', max_length=80, verbose_name='frequência')),
                ('inicio', models.DateField(verbose_name='início')),
                ('fim', models.DateField(blank=True, help_text='Vazio = uso contínuo', null=True, verbose_name='fim')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('acolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicacoes', to='acolhidos.acolhido')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'medicação',
                'verbose_name_plural': 'medicações',
                'ordering': ['nome'],
            },
            managers=[
                ('em_vigor', django.db.models.manager.Manager()),
            ],
        ),
    ]
