# Generated by Django 5.2.17 on 2026-09-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhidos', '0002_ficha_saude_cuidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaacolhimento',
            name='observacao_desligamento',
            field=models.TextField(blank=True, verbose_name='observação do desligamento'),
        ),
        migrations.AddField(
            model_name='historicalfichaacolhimento',
            name='observacao_desligamento',
            field=models.TextField(blank=True, verbose_name='observação do desligamento'),
        ),
        migrations.AlterField(
            model_name='fichaacolhimento',
            name='destino',
            field=models.CharField(blank=True, choices=[('REINTEGRACAO', 'Reintegração familiar'), ('ADOCAO', 'Adoção'), ('MAIORIDADE', 'Maioridade'), ('TRANSFERENCIA', 'Transferência para outra instituição'), ('OUTRO', 'Outro')], max_length=150, verbose_name='destino após o desligamento'),
        ),
        migrations.AlterField(
            model_name='historicalfichaacolhimento',
            name='destino',
            field=models.CharField(blank=True, choices=[('REINTEGRACAO', 'Reintegração familiar'), ('ADOCAO', 'Adoção'), ('MAIORIDADE', 'Maioridade'), ('TRANSFERENCIA', 'Transferência para outra instituição'), ('OUTRO', 'Outro')], max_length=150, verbose_name='destino após o desligamento'),
        ),
    ]
