# Generated by Django 5.2.17 on 2026-09-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acolhidos', '0003_desligamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicacao',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'ordering': ['nome'], 'verbose_name': 'medicação', 'verbose_name_plural': 'medicações'},
        ),
        migrations.AlterModelManagers(
            name='medicacao',
            managers=[
            ],
        ),
    ]
