# Generated by Django 5.2.17 on 2026-09-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhidos', '0004_manager_medicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossaude',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='tipo sanguíneo'),
        ),
        migrations.AlterField(
            model_name='historicaldadossaude',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='tipo sanguíneo'),
        ),
    ]
