# Generated by Django 5.2.17 on 2026-09-24 13:08

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doacoes', '0003_metaitemcampanha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('tem_validade', models.BooleanField(default=False, help_text='Marque para alimentos e outros itens que vencem.', verbose_name='tem data de validade')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'categoria de item',
                'verbose_name_plural': 'categorias de itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='estoque.categoriaitem', verbose_name='categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'item do estoque',
                'verbose_name_plural': 'itens do estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantidade_inicial', models.PositiveIntegerField(verbose_name='quantidade recebida')),
                ('saldo', models.PositiveIntegerField(verbose_name='quantidade disponível')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('doacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lote_estoque', to='doacoes.doacao')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='estoque.itemestoque')),
            ],
            options={
                'verbose_name': 'lote do estoque',
                'verbose_name_plural': 'lotes do estoque',
                'ordering': [models.OrderBy(models.F('validade'), nulls_last=True), 'criado_em', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='tipo')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.itemestoque')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.loteestoque')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimentação do estoque',
                'verbose_name_plural': 'movimentações do estoque',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriaitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='categoria_item_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='itemestoque',
            constraint=models.UniqueConstraint(models.F('categoria'), django.db.models.functions.text.Lower('nome'), name='item_estoque_nome_unico_na_categoria'),
        ),
        migrations.AddConstraint(
            model_name='loteestoque',
            constraint=models.CheckConstraint(condition=models.Q(('saldo__lte', models.F('quantidade_inicial'))), name='lote_saldo_nao_passa_do_recebido'),
        ),
    ]
