# Generated by Django 5.2.17 on 2026-09-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_arquivo_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoenviado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
