# Generated by Django 5.2.17 on 2026-09-23 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voluntarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('data_inicio', models.DateField(verbose_name='início')),
                ('data_fim', models.DateField(verbose_name='término')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADA', 'Publicada')], default='RASCUNHO', max_length=10, verbose_name='situação')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'escala',
                'verbose_name_plural': 'escalas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('data', models.DateField(verbose_name='data')),
                ('hora_inicio', models.TimeField(verbose_name='início')),
                ('hora_fim', models.TimeField(verbose_name='término')),
                ('vagas', models.PositiveSmallIntegerField(default=1, verbose_name='vagas')),
                ('observacoes', models.CharField(blank=True, max_length=200, verbose_name='observações')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='escalas.atividade')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='escalas.escala')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('status', models.CharField(choices=[('PREVISTO', 'Previsto'), ('CONFIRMADO', 'Compareceu'), ('FALTOU', 'Faltou')], default='PREVISTO', max_length=10, verbose_name='situação')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='voluntarios.voluntario')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='escalas.turno')),
            ],
            options={
                'verbose_name': 'alocação',
                'verbose_name_plural': 'alocações',
                'constraints': [models.UniqueConstraint(fields=('turno', 'voluntario'), name='alocacao_unica_por_turno')],
            },
        ),
    ]
