# Generated by Django 5.2.17 on 2026-09-24 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
        ('voluntarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='voluntario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='voluntarios.voluntario'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(fields=('turno', 'usuario'), name='alocacao_usuario_unica_por_turno'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('usuario__isnull', True), ('voluntario__isnull', False)), models.Q(('usuario__isnull', False), ('voluntario__isnull', True)), _connector='OR'), name='alocacao_exatamente_um_responsavel'),
        ),
    ]
