# Generated by Django 5.2.17 on 2026-09-22 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_email_unico'),
        ('acolhidos', '0002_ficha_saude_cuidado'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcessoFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_descricao', models.CharField(blank=True, max_length=200, verbose_name='usuário')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('acao', models.CharField(choices=[('VIEW', 'Consultou'), ('EDIT', 'Alterou')], max_length=5, verbose_name='ação')),
                ('acolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='acolhidos.acolhido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_ficha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acesso a ficha',
                'verbose_name_plural': 'acessos a fichas',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['acolhido', '-data_hora'], name='accounts_lo_acolhid_2f1185_idx')],
            },
        ),
    ]
