# Generated by Django 5.2.17 on 2026-09-23 15:09

import core.uploads
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'função',
                'verbose_name_plural': 'funções',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=150, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=80, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('data_cadastro', models.DateField(default=datetime.date.today, verbose_name='data de cadastro')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10, verbose_name='situação')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntarios_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('funcoes', models.ManyToManyField(blank=True, related_name='voluntarios', to='voluntarios.funcao', verbose_name='funções')),
            ],
            options={
                'verbose_name': 'voluntário',
                'verbose_name_plural': 'voluntários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('arquivo', models.FileField(upload_to=core.uploads.CaminhoOpaco('voluntarios/documentos'), validators=[core.uploads.validar_documento], verbose_name='arquivo')),
                ('tipo', models.CharField(max_length=80, verbose_name='tipo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=6, verbose_name='turno')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'disponibilidade',
                'verbose_name_plural': 'disponibilidades',
                'ordering': ['dia_semana', 'turno'],
                'constraints': [models.UniqueConstraint(fields=('voluntario', 'dia_semana', 'turno'), name='disponibilidade_unica')],
            },
        ),
    ]
