# Generated by Django 5.2.17 on 2026-09-22 17:54

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data_inicio', models.DateField(verbose_name='início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='término')),
                ('meta_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='meta em reais')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'campanha',
                'verbose_name_plural': 'campanhas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=150, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=80, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa física'), ('PJ', 'Pessoa jurídica')], default='PF', max_length=2, verbose_name='tipo')),
                ('nome', models.CharField(max_length=150, verbose_name='nome ou razão social')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, verbose_name='CPF ou CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('recorrente', models.BooleanField(default=False, help_text='Marque se a pessoa ou empresa doa com regularidade.', verbose_name='doador recorrente')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doadores_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doador',
                'verbose_name_plural': 'doadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDoacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('tipo', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('ALIMENTO', 'Alimento'), ('VESTUARIO', 'Vestuário'), ('MATERIAL', 'Material'), ('SERVICO', 'Serviço'), ('OUTRO', 'Outro')], max_length=10, verbose_name='tipo')),
                ('descricao', models.CharField(blank=True, help_text='Ex.: Arroz 5kg, cobertores', max_length=200, verbose_name='descrição')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quantidade')),
                ('unidade', models.CharField(blank=True, help_text='Ex.: pacotes, caixas, peças', max_length=30, verbose_name='unidade')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor em reais')),
                ('data_recebimento', models.DateField(default=datetime.date.today, verbose_name='data de recebimento')),
                ('recibo_emitido', models.BooleanField(default=False, verbose_name='recibo emitido')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('campanha', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='doacoes.campanha')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('doador', models.ForeignKey(blank=True, db_constraint=False, help_text='Deixe vazio para doação anônima.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='doacoes.doador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recebido_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical doação',
                'verbose_name_plural': 'historical doações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='excluido em')),
                ('tipo', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('ALIMENTO', 'Alimento'), ('VESTUARIO', 'Vestuário'), ('MATERIAL', 'Material'), ('SERVICO', 'Serviço'), ('OUTRO', 'Outro')], max_length=10, verbose_name='tipo')),
                ('descricao', models.CharField(blank=True, help_text='Ex.: Arroz 5kg, cobertores', max_length=200, verbose_name='descrição')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quantidade')),
                ('unidade', models.CharField(blank=True, help_text='Ex.: pacotes, caixas, peças', max_length=30, verbose_name='unidade')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor em reais')),
                ('data_recebimento', models.DateField(default=datetime.date.today, verbose_name='data de recebimento')),
                ('recibo_emitido', models.BooleanField(default=False, verbose_name='recibo emitido')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes', to='doacoes.campanha')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('doador', models.ForeignKey(blank=True, help_text='Deixe vazio para doação anônima.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes', to='doacoes.doador')),
            ],
            options={
                'verbose_name': 'doação',
                'verbose_name_plural': 'doações',
                'ordering': ['-data_recebimento', '-criado_em'],
                'indexes': [models.Index(fields=['-data_recebimento'], name='doacoes_doa_data_re_08341e_idx')],
            },
        ),
    ]
