# Generated by Django 5.2.17 on 2026-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='encerrada_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='encerrada em'),
        ),
    ]
