# Generated by Django 5.2.17 on 2026-09-23 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0002_campanha_encerrada_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaItemCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALIMENTO', 'Alimento'), ('VESTUARIO', 'Vestuário'), ('MATERIAL', 'Material'), ('SERVICO', 'Serviço'), ('OUTRO', 'Outro')], max_length=10, verbose_name='tipo de item')),
                ('quantidade', models.PositiveIntegerField(verbose_name='quantidade desejada')),
                ('unidade', models.CharField(choices=[('unidades', 'Unidade'), ('pacotes', 'Pacote'), ('caixas', 'Caixa'), ('peças', 'Peças'), ('pares', 'Par'), ('sacos', 'Saco'), ('fardos', 'Fardo'), ('quilos', 'Quilo'), ('litros', 'Litro'), ('horas', 'Hora')], max_length=30, verbose_name='unidade')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_itens', to='doacoes.campanha')),
            ],
            options={
                'verbose_name': 'meta de item',
                'verbose_name_plural': 'metas de itens',
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('campanha', 'tipo', 'unidade'), name='meta_item_campanha_unica')],
            },
        ),
    ]
