# Generated by Django 5.2.17 on 2026-09-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0004_itens_somente_em_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaitemcampanha',
            name='unidade',
            field=models.CharField(choices=[('unidades', 'Unidade'), ('horas', 'Hora')], max_length=30, verbose_name='unidade'),
        ),
    ]
