# Generated by Django 5.2.17 on 2026-09-24 13:58

import django.db.models.deletion
from django.db import migrations, models


# Tipos antigos viram "Itens" com a categoria do estoque equivalente.
CATEGORIA_DO_TIPO = {
    "ALIMENTO": ("Alimentos", True),
    "VESTUARIO": ("Vestuário", False),
    "MATERIAL": ("Outros", False),
    "OUTRO": ("Outros", False),
}


def converter_tipos(apps, schema_editor):
    CategoriaItem = apps.get_model("estoque", "CategoriaItem")
    modelos = [apps.get_model("doacoes", nome)
               for nome in ("Doacao", "HistoricalDoacao", "MetaItemCampanha")]
    for antigo, (nome, tem_validade) in CATEGORIA_DO_TIPO.items():
        if not any(m.objects.filter(tipo=antigo).exists() for m in modelos):
            continue
        categoria = CategoriaItem.objects.filter(nome__iexact=nome).first()
        if categoria is None:
            categoria = CategoriaItem.objects.create(nome=nome, tem_validade=tem_validade)
        for modelo in modelos:
            modelo.objects.filter(tipo=antigo).update(tipo="ITEM", categoria_id=categoria.pk)
    # Duas metas antigas (Material e Outro) podem ter caido na mesma categoria.
    Meta = modelos[2]
    vistas = set()
    for meta in Meta.objects.order_by("pk"):
        chave = (meta.campanha_id, meta.tipo, meta.categoria_id, meta.unidade)
        if chave in vistas:
            meta.delete()
        vistas.add(chave)


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0005_alter_metaitemcampanha_unidade'),
        ('estoque', '0002_categorias_iniciais'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metaitemcampanha',
            name='meta_item_campanha_unica',
        ),
        migrations.AddField(
            model_name='doacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doacoes', to='estoque.categoriaitem', verbose_name='categoria no estoque'),
        ),
        migrations.AddField(
            model_name='historicaldoacao',
            name='categoria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estoque.categoriaitem', verbose_name='categoria no estoque'),
        ),
        migrations.AddField(
            model_name='metaitemcampanha',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metas_campanha', to='estoque.categoriaitem', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='tipo',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('ITEM', 'Itens'), ('SERVICO', 'Serviço')], max_length=10, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='historicaldoacao',
            name='tipo',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('ITEM', 'Itens'), ('SERVICO', 'Serviço')], max_length=10, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='metaitemcampanha',
            name='tipo',
            field=models.CharField(choices=[('ITEM', 'Itens'), ('SERVICO', 'Serviço')], max_length=10, verbose_name='tipo de item'),
        ),
        migrations.RunPython(converter_tipos, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='metaitemcampanha',
            constraint=models.UniqueConstraint(fields=('campanha', 'tipo', 'categoria', 'unidade'), name='meta_item_campanha_unica'),
        ),
    ]
